[package]
name = "trapd-detection"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
[dependencies]
trapd-schema = { path = "../trapd-schema" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
anyhow = "1"
tracing = "0.1"
globset = "0.4"
regex = "1.12.3"
serde_yaml_ng = "0.10"
sha2 = "0.10"
hex = "0.4"
yara-rust = { version = "0.28", package = "yara", optional = true }
[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
[features]
yara = ["dep:yara-rust"]
