#!/usr/bin/env bash
# TRAPD Agent Installer
# Usage (manual):
#   sudo TRAPD_BACKEND_URL=https://api.example.com \
#        TRAPD_ENROLL_TOKEN=enroll_xxxx \
#        bash install.sh
#
# Usage (one-click, generated by dashboard):
#   curl -fsSL "https://api.example.com/install.sh?token=enroll_xxxx" | sudo bash
set -euo pipefail

REPO="trapd-cloud/trapd-agent"
BINARY_NAME="trapd-agent-linux-x86_64"
EBPF_BINARY_NAME="trapd-agent-exec"
INSTALL_BIN="/usr/local/bin/trapd-agent"
EBPF_INSTALL_DIR="/usr/lib/trapd-agent"
EBPF_INSTALL_BIN="${EBPF_INSTALL_DIR}/trapd-agent-exec"
UPDATE_BIN="/usr/local/bin/trapd-update"
SERVICE_FILE="/etc/systemd/system/trapd-agent.service"
UPDATE_SERVICE_FILE="/etc/systemd/system/trapd-update.service"
UPDATE_TIMER_FILE="/etc/systemd/system/trapd-update.timer"
LOGROTATE_FILE="/etc/logrotate.d/trapd"
ENV_DIR="/etc/trapd"
LOG_DIR="/var/log/trapd"

# ── Preflight checks ────────────────────────────────────────────────────────
for cmd in curl systemctl; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "ERROR: '$cmd' is required but not installed." >&2
        exit 1
    fi
done

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (sudo)." >&2
    exit 1
fi

# ── Fetch latest release tag ────────────────────────────────────────────────
echo "Fetching latest release..."
LATEST_TAG=$(curl -sf "https://api.github.com/repos/${REPO}/releases/latest" \
    | grep '"tag_name"' \
    | head -1 \
    | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')

if [[ -z "$LATEST_TAG" ]]; then
    echo "ERROR: Could not determine latest release tag from GitHub API." >&2
    exit 1
fi

echo "Latest release: ${LATEST_TAG}"

# ── Download agent binary ────────────────────────────────────────────────────
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${LATEST_TAG}/${BINARY_NAME}"
TMP_BINARY="/tmp/trapd-agent-${LATEST_TAG}"

echo "Downloading ${BINARY_NAME}..."
curl -fL "$DOWNLOAD_URL" -o "$TMP_BINARY"
chmod +x "$TMP_BINARY"
mv -f "$TMP_BINARY" "$INSTALL_BIN"
echo "Installed to ${INSTALL_BIN}"

# ── Download eBPF binary ─────────────────────────────────────────────────────
EBPF_URL="https://github.com/${REPO}/releases/download/${LATEST_TAG}/${EBPF_BINARY_NAME}"
TMP_EBPF="/tmp/trapd-agent-exec-${LATEST_TAG}"

echo "Downloading ${EBPF_BINARY_NAME}..."
mkdir -p "$EBPF_INSTALL_DIR"
if curl -fL "$EBPF_URL" -o "$TMP_EBPF" 2>/dev/null; then
    chmod 644 "$TMP_EBPF"
    mv -f "$TMP_EBPF" "$EBPF_INSTALL_BIN"
    echo "eBPF program installed to ${EBPF_INSTALL_BIN}"
else
    echo "WARNING: eBPF binary not found in release — kernel-side pre-exec blocking disabled." >&2
fi

# ── Create directories ───────────────────────────────────────────────────────
mkdir -p "$ENV_DIR" "$LOG_DIR"

# ── Write agent.env (from env vars if provided) ──────────────────────────────
ENV_FILE="${ENV_DIR}/agent.env"

if [[ -n "${TRAPD_BACKEND_URL:-}" && -n "${TRAPD_ENROLL_TOKEN:-}" ]]; then
    echo "Writing agent config to ${ENV_FILE}..."
    cat > "$ENV_FILE" <<ENVEOF
TRAPD_BACKEND_URL=${TRAPD_BACKEND_URL}
TRAPD_ENROLL_TOKEN=${TRAPD_ENROLL_TOKEN}
TRAPD_OUTPUT=file
RUST_LOG=info
ENVEOF
    chmod 600 "$ENV_FILE"
    echo "Config written — agent will enroll automatically on first start."
elif [[ ! -f "$ENV_FILE" ]]; then
    echo ""
    echo "⚠️  TRAPD_BACKEND_URL or TRAPD_ENROLL_TOKEN not set."
    echo "   Edit ${ENV_FILE} before starting the agent:"
    cat > "$ENV_FILE" <<ENVEOF
TRAPD_BACKEND_URL=https://your-backend.example.com
TRAPD_ENROLL_TOKEN=enroll_xxxx
TRAPD_OUTPUT=file
RUST_LOG=info
ENVEOF
    chmod 600 "$ENV_FILE"
fi

# ── Write trapd-agent.service ────────────────────────────────────────────────
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=TRAPD Security Agent
After=network.target

[Service]
ExecStart=/usr/local/bin/trapd-agent
Restart=always
RestartSec=5
EnvironmentFile=/etc/trapd/agent.env
Environment=TRAPD_EBPF_PATH=${EBPF_INSTALL_BIN}

# Capabilities for eBPF loading, network containment and file quarantine
CapabilityBoundingSet=CAP_NET_ADMIN CAP_SYS_PTRACE CAP_BPF CAP_PERFMON CAP_NET_RAW CAP_IPC_LOCK CAP_LINUX_IMMUTABLE

[Install]
WantedBy=multi-user.target
EOF

# ── Write trapd-update script ────────────────────────────────────────────────
cat > "$UPDATE_BIN" <<UPDATER
#!/usr/bin/env bash
set -euo pipefail

REPO="${REPO}"
BINARY_NAME="${BINARY_NAME}"
EBPF_BINARY_NAME="${EBPF_BINARY_NAME}"
INSTALL_BIN="${INSTALL_BIN}"
EBPF_INSTALL_DIR="${EBPF_INSTALL_DIR}"
EBPF_INSTALL_BIN="${EBPF_INSTALL_BIN}"

log() { echo "\$(date -u +"%Y-%m-%dT%H:%M:%SZ") trapd-update: \$*"; }

LATEST_TAG=\$(curl -sf "https://api.github.com/repos/\${REPO}/releases/latest" \\
    | grep '"tag_name"' \\
    | head -1 \\
    | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')

if [[ -z "\$LATEST_TAG" ]]; then
    log "ERROR: Could not fetch latest release tag." >&2
    exit 1
fi

CURRENT_VERSION=\$("\$INSTALL_BIN" --version 2>/dev/null | awk '{print \$2}' || echo "unknown")
LATEST_VERSION="\${LATEST_TAG#v}"

if [[ "\$CURRENT_VERSION" == "\$LATEST_VERSION" ]]; then
    log "Already up to date (\$CURRENT_VERSION)."
    exit 0
fi

log "Updating \$CURRENT_VERSION → \$LATEST_TAG..."

DOWNLOAD_URL="https://github.com/\${REPO}/releases/download/\${LATEST_TAG}/\${BINARY_NAME}"
TMP_BINARY="/tmp/trapd-agent-new"
curl -fL "\$DOWNLOAD_URL" -o "\$TMP_BINARY"
chmod +x "\$TMP_BINARY"
mv -f "\$TMP_BINARY" "\$INSTALL_BIN"

EBPF_URL="https://github.com/\${REPO}/releases/download/\${LATEST_TAG}/\${EBPF_BINARY_NAME}"
TMP_EBPF="/tmp/trapd-agent-exec-new"
if curl -fL "\$EBPF_URL" -o "\$TMP_EBPF" 2>/dev/null; then
    chmod 644 "\$TMP_EBPF"
    mkdir -p "\$EBPF_INSTALL_DIR"
    mv -f "\$TMP_EBPF" "\$EBPF_INSTALL_BIN"
    log "eBPF binary updated."
fi

systemctl restart trapd-agent
log "Updated to \${LATEST_TAG}."
UPDATER

chmod +x "$UPDATE_BIN"

# ── Write update service + timer ─────────────────────────────────────────────
cat > "$UPDATE_SERVICE_FILE" <<'EOF'
[Unit]
Description=TRAPD Agent Auto-Update
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/trapd-update
EOF

cat > "$UPDATE_TIMER_FILE" <<'EOF'
[Unit]
Description=Daily TRAPD Agent Auto-Update

[Timer]
OnCalendar=*-*-* 03:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF

# ── Logrotate config ──────────────────────────────────────────────────────────
cat > "$LOGROTATE_FILE" <<'EOF'
/var/log/trapd/events.ndjson {
    daily
    rotate 14
    compress
    missingok
    notifempty
    create 0640 root root
}
EOF

# ── Enable services ───────────────────────────────────────────────────────────
systemctl daemon-reload
systemctl enable --now trapd-agent
systemctl enable --now trapd-update.timer

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "✅ TRAPD Agent ${LATEST_TAG} installed and started."
echo ""
if systemctl is-active --quiet trapd-agent; then
    echo "   Status: running"
    echo "   Logs:   journalctl -u trapd-agent -f"
else
    echo "   Status: check 'journalctl -u trapd-agent' for errors"
fi
