#!/usr/bin/env bash
# TRAPD Agent Installer
# Usage (manual):
#   sudo TRAPD_BACKEND_URL=https://api.example.com \
#        TRAPD_ENROLL_TOKEN=enroll_xxxx \
#        bash install.sh
#
# Usage (one-click, generated by dashboard):
#   curl -fsSL "https://api.example.com/install.sh?token=enroll_xxxx" | sudo bash
set -euo pipefail

REPO="trapd-cloud/trapd-agent"
BINARY_NAME="trapd-agent-linux-x86_64"
EBPF_BINARY_NAME="trapd-agent-exec"
INSTALL_BIN="/usr/local/bin/trapd-agent"
EBPF_INSTALL_DIR="/usr/lib/trapd-agent"
EBPF_INSTALL_BIN="${EBPF_INSTALL_DIR}/trapd-agent-exec"
UPDATE_BIN="/usr/local/bin/trapd-update"
SERVICE_FILE="/etc/systemd/system/trapd-agent.service"
UPDATE_SERVICE_FILE="/etc/systemd/system/trapd-update.service"
UPDATE_TIMER_FILE="/etc/systemd/system/trapd-update.timer"
LOGROTATE_FILE="/etc/logrotate.d/trapd"
ENV_DIR="/etc/trapd"
LOG_DIR="/var/log/trapd"
STATE_DIR="/var/lib/trapd"

# ── Preflight checks ────────────────────────────────────────────────────────
for cmd in curl systemctl sha256sum; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "ERROR: '$cmd' is required but not installed." >&2
        exit 1
    fi
done

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (sudo)." >&2
    exit 1
fi

# ── Integrity verification ───────────────────────────────────────────────────
# Download the published SHA256 for an artifact and verify the local copy
# *before* it is installed as root.  A missing or mismatching checksum aborts
# the install — an unverified root binary is never trusted.  This closes the
# supply-chain window where a MITM/CDN/registry compromise could swap the
# binary for malicious code (the download uses HTTPS, but TLS alone does not
# protect against a rogue CA or a tampered release asset).
verify_checksum() {
    local file="$1" sums_url="$2" sums_file
    sums_file="$(mktemp)"
    if ! curl -fsSL "$sums_url" -o "$sums_file"; then
        rm -f "$sums_file"
        echo "ERROR: could not download checksum ($sums_url)." >&2
        echo "       Refusing to install an unverified binary." >&2
        exit 1
    fi
    local expected actual
    expected="$(awk '{print $1}' "$sums_file" | head -1)"
    actual="$(sha256sum "$file" | awk '{print $1}')"
    rm -f "$sums_file"
    if [[ -z "$expected" || "$expected" != "$actual" ]]; then
        echo "ERROR: SHA256 mismatch for ${file##*/} — binary may have been tampered with." >&2
        echo "       expected: ${expected:-<empty>}" >&2
        echo "       actual:   ${actual}" >&2
        exit 1
    fi
    echo "Checksum verified (${actual})."
}

# ── Fetch latest release tag ────────────────────────────────────────────────
echo "Fetching latest release..."
LATEST_TAG=$(curl -sf "https://api.github.com/repos/${REPO}/releases/latest" \
    | grep '"tag_name"' \
    | head -1 \
    | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')

if [[ -z "$LATEST_TAG" ]]; then
    echo "ERROR: Could not determine latest release tag from GitHub API." >&2
    exit 1
fi

echo "Latest release: ${LATEST_TAG}"

# ── Download agent binary ────────────────────────────────────────────────────
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${LATEST_TAG}/${BINARY_NAME}"
TMP_BINARY="/tmp/trapd-agent-${LATEST_TAG}"

echo "Downloading ${BINARY_NAME}..."
curl -fL "$DOWNLOAD_URL" -o "$TMP_BINARY"
verify_checksum "$TMP_BINARY" "${DOWNLOAD_URL}.sha256"
chmod +x "$TMP_BINARY"
mv -f "$TMP_BINARY" "$INSTALL_BIN"
echo "Installed to ${INSTALL_BIN}"

# ── Download eBPF binary ─────────────────────────────────────────────────────
EBPF_URL="https://github.com/${REPO}/releases/download/${LATEST_TAG}/${EBPF_BINARY_NAME}"
TMP_EBPF="/tmp/trapd-agent-exec-${LATEST_TAG}"

echo "Downloading ${EBPF_BINARY_NAME}..."
mkdir -p "$EBPF_INSTALL_DIR"
if curl -fL "$EBPF_URL" -o "$TMP_EBPF" 2>/dev/null; then
    verify_checksum "$TMP_EBPF" "${EBPF_URL}.sha256"
    chmod 644 "$TMP_EBPF"
    mv -f "$TMP_EBPF" "$EBPF_INSTALL_BIN"
    echo "eBPF program installed to ${EBPF_INSTALL_BIN}"
else
    echo "WARNING: eBPF binary not found in release — kernel-side pre-exec blocking disabled." >&2
fi

# ── Create directories ───────────────────────────────────────────────────────
# systemd's StateDirectory=/LogsDirectory= also create these, but doing it here
# keeps a manual (non-systemd) run working too.
mkdir -p "$ENV_DIR" "$LOG_DIR" "$STATE_DIR"
chmod 700 "$STATE_DIR"

# ── Write agent.env (from env vars if provided) ──────────────────────────────
ENV_FILE="${ENV_DIR}/agent.env"

# Strip any trailing slash from the backend URL so the agent never builds
# double-slash request paths.
TRAPD_BACKEND_URL="${TRAPD_BACKEND_URL:-}"
TRAPD_BACKEND_URL="${TRAPD_BACKEND_URL%/}"

if [[ -n "${TRAPD_BACKEND_URL}" && -n "${TRAPD_ENROLL_TOKEN:-}" ]]; then
    echo "Writing agent config to ${ENV_FILE}..."
    cat > "$ENV_FILE" <<ENVEOF
TRAPD_BACKEND_URL=${TRAPD_BACKEND_URL}
TRAPD_ENROLL_TOKEN=${TRAPD_ENROLL_TOKEN}
TRAPD_OUTPUT=file
RUST_LOG=info
ENVEOF
    chmod 600 "$ENV_FILE"
    echo "Config written — agent will enroll automatically on first start."
elif [[ -f "$ENV_FILE" ]]; then
    echo "Keeping existing ${ENV_FILE} (not overwriting)."
else
    echo ""
    echo "⚠️  TRAPD_BACKEND_URL or TRAPD_ENROLL_TOKEN not set."
    echo "   Edit ${ENV_FILE} before starting the agent:"
    cat > "$ENV_FILE" <<ENVEOF
TRAPD_BACKEND_URL=https://your-backend.example.com
TRAPD_ENROLL_TOKEN=enroll_xxxx
TRAPD_OUTPUT=file
RUST_LOG=info
ENVEOF
    chmod 600 "$ENV_FILE"
fi

# ── Write trapd-agent.service (hardened, $HOME-independent) ───────────────────
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=TRAPD Security Agent
Documentation=https://github.com/trapd-cloud/trapd-agent
After=network.target network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/trapd-agent
Restart=always
RestartSec=5
TimeoutStopSec=30

Environment=TRAPD_OUTPUT=file
Environment=RUST_LOG=info
# Canonical, \$HOME-independent locations.  Setting these explicitly means the
# agent never depends on systemd providing \$HOME (it does not for system
# services) — this was the historical enrollment crash-loop root cause.
Environment=TRAPD_STATE_DIR=${STATE_DIR}
Environment=TRAPD_CONFIG_DIR=${ENV_DIR}
Environment=TRAPD_LOG_DIR=${LOG_DIR}
Environment=HOME=${STATE_DIR}
Environment=TRAPD_EBPF_PATH=${EBPF_INSTALL_BIN}
EnvironmentFile=-/etc/trapd/agent.env

# systemd creates/owns these with correct permissions on every start.
StateDirectory=trapd
StateDirectoryMode=0700
LogsDirectory=trapd
ConfigurationDirectory=trapd

# ── Hardening ────────────────────────────────────────────────────────────────
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=-/etc/trapd -/var/lib/trapd -/var/log/trapd
NoNewPrivileges=true
# Capabilities for eBPF loading, network containment and file quarantine.
CapabilityBoundingSet=CAP_NET_ADMIN CAP_SYS_PTRACE CAP_BPF CAP_PERFMON CAP_NET_RAW CAP_IPC_LOCK CAP_LINUX_IMMUTABLE
MemoryDenyWriteExecute=true
LockPersonality=true
RestrictRealtime=true
RestrictSUIDSGID=true
RemoveIPC=true
ProtectControlGroups=true
SystemCallFilter=@system-service @network-io @file-system @process bpf perf_event_open
SystemCallErrorNumber=EPERM
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
EOF

# ── Write trapd-update script ────────────────────────────────────────────────
cat > "$UPDATE_BIN" <<UPDATER
#!/usr/bin/env bash
set -euo pipefail

REPO="${REPO}"
BINARY_NAME="${BINARY_NAME}"
EBPF_BINARY_NAME="${EBPF_BINARY_NAME}"
INSTALL_BIN="${INSTALL_BIN}"
EBPF_INSTALL_DIR="${EBPF_INSTALL_DIR}"
EBPF_INSTALL_BIN="${EBPF_INSTALL_BIN}"

log() { echo "\$(date -u +"%Y-%m-%dT%H:%M:%SZ") trapd-update: \$*"; }

# Verify a downloaded artifact against its published SHA256 before installing it
# as root.  A missing or mismatching checksum aborts the update so a tampered
# release asset can never replace the running agent binary.
verify_checksum() {
    local file="\$1" sums_url="\$2" sums_file
    sums_file="\$(mktemp)"
    if ! curl -fsSL "\$sums_url" -o "\$sums_file"; then
        rm -f "\$sums_file"
        log "ERROR: could not download checksum (\$sums_url) — refusing unverified binary." >&2
        exit 1
    fi
    local expected actual
    expected="\$(awk '{print \$1}' "\$sums_file" | head -1)"
    actual="\$(sha256sum "\$file" | awk '{print \$1}')"
    rm -f "\$sums_file"
    if [[ -z "\$expected" || "\$expected" != "\$actual" ]]; then
        log "ERROR: SHA256 mismatch for \${file##*/} — binary may have been tampered with." >&2
        exit 1
    fi
}

LATEST_TAG=\$(curl -sf "https://api.github.com/repos/\${REPO}/releases/latest" \\
    | grep '"tag_name"' \\
    | head -1 \\
    | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')

if [[ -z "\$LATEST_TAG" ]]; then
    log "ERROR: Could not fetch latest release tag." >&2
    exit 1
fi

CURRENT_VERSION=\$("\$INSTALL_BIN" --version 2>/dev/null | awk '{print \$2}' || echo "unknown")
LATEST_VERSION="\${LATEST_TAG#v}"

if [[ "\$CURRENT_VERSION" == "\$LATEST_VERSION" ]]; then
    log "Already up to date (\$CURRENT_VERSION)."
    exit 0
fi

log "Updating \$CURRENT_VERSION → \$LATEST_TAG..."

DOWNLOAD_URL="https://github.com/\${REPO}/releases/download/\${LATEST_TAG}/\${BINARY_NAME}"
TMP_BINARY="/tmp/trapd-agent-new"
curl -fL "\$DOWNLOAD_URL" -o "\$TMP_BINARY"
verify_checksum "\$TMP_BINARY" "\${DOWNLOAD_URL}.sha256"
chmod +x "\$TMP_BINARY"
mv -f "\$TMP_BINARY" "\$INSTALL_BIN"

EBPF_URL="https://github.com/\${REPO}/releases/download/\${LATEST_TAG}/\${EBPF_BINARY_NAME}"
TMP_EBPF="/tmp/trapd-agent-exec-new"
if curl -fL "\$EBPF_URL" -o "\$TMP_EBPF" 2>/dev/null; then
    verify_checksum "\$TMP_EBPF" "\${EBPF_URL}.sha256"
    chmod 644 "\$TMP_EBPF"
    mkdir -p "\$EBPF_INSTALL_DIR"
    mv -f "\$TMP_EBPF" "\$EBPF_INSTALL_BIN"
    log "eBPF binary updated."
fi

systemctl restart trapd-agent
log "Updated to \${LATEST_TAG}."
UPDATER

chmod +x "$UPDATE_BIN"

# ── Write update service + timer ─────────────────────────────────────────────
cat > "$UPDATE_SERVICE_FILE" <<'EOF'
[Unit]
Description=TRAPD Agent Auto-Update
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/trapd-update
EOF

cat > "$UPDATE_TIMER_FILE" <<'EOF'
[Unit]
Description=Daily TRAPD Agent Auto-Update

[Timer]
OnCalendar=*-*-* 03:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF

# ── Logrotate config ──────────────────────────────────────────────────────────
cat > "$LOGROTATE_FILE" <<'EOF'
/var/log/trapd/events.ndjson {
    daily
    rotate 14
    compress
    missingok
    notifempty
    create 0640 root root
}
EOF

# ── Enable services ───────────────────────────────────────────────────────────
systemctl daemon-reload
systemctl enable --now trapd-agent
systemctl enable --now trapd-update.timer

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "✅ TRAPD Agent ${LATEST_TAG} installed and started."
echo ""
if systemctl is-active --quiet trapd-agent; then
    echo "   Status: running"
    echo "   Logs:   journalctl -u trapd-agent -f"
else
    echo "   Status: check 'journalctl -u trapd-agent' for errors"
fi
